name: Deploy to EC2

on:
  push:
    branches:
      - main # 배포할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/bluffing-backend/2025_SEASONTHON_TEAM_87_BE
            git pull origin feat/jam759
            ./gradlew clean build
            # 기존 실행 프로세스 종료
            pkill -f 'java -jar build/libs/bluffing-0.0.1-SNAPSHOT.jar' || true
            # 백그라운드 실행
            nohup java -jar build/libs/bluffing-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
