version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bluffing-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bluffing
      LANG: ko_KR.UTF-8
      LC_ALL: ko_KR.UTF-8
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
